version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5433:5432
